---
title: "Group 8 - Proyecto Pre-entrega"
output: html_notebook
---

# Integrantes
- Aleskyjubinsl Alcarraz Jaime
- Alvaro Guerrero Jiménez
- Henrry De La Cruz Urrutia
- Marcelo Franco Loayza Taboada
- Marcos Junior Mamani Avalos

## Temas propuestos
                                                       
Describir cualitativa y cuantitativamente a los investigadores registrados en el
RENACYT Analizar la percepción sobre las próximas elecciones municipales y
regionales por parte de alumnos de la UTEC Describir una relación entre perfiles
de estudiantes y su desempeño académico

## Primer tema
Describir cualitativa y cuantitativamente a los investigadores registrados en el
RENACYT

### Relevancia
Estudiamos en una universidad de ingeniería, para sus alumnos, una posibilidad
de trayectoria vocacional es la investigación. Por ello, pueden estar
interesados en el perfil del investigador peruano. También podremos juzgar la
participación femenina en un área dominada por el género masculino. Todo esto
con datos actualizados hasta el 2022-02-25.

### Factibilidad
Los datos ya han sido recolectados en el _Registro Nacional Científico,
Tecnológico y de Innovación Tecnológica_ (RENACYT). Están disponibles en la
[_Plataforma Nacional de Datos
Abiertos_](https://www.datosabiertos.gob.pe/dataset/registro-nacional-de-investigadores-renacyt)
en formato XLSX. Fueron convertidos a formato CSV mediante los comandos:


```{r}
library(readxl)
renacyt <- read_excel("RENACYT 24022022.xlsx")
write.csv(renacyt, file = "RENACYT 24022022.csv")
```

### Descripción de variables
#### `codigo_renacyt`
Variable categórica nominal  
ID asignada por el RENACYT a cada investigador.

#### `Investigador`
Variable categórica nominal  
Nombre del investigador

#### `Genero`
Variable categórica nominal  
Género del investigador (`Masculino` o `Femenino`)

#### `URL_CTI_Vitae`
Variable categórica nominal  
URL del investigador  
Actualmente inaccesible

#### `grupo`
Variable categórica nominal  
Clasificación de los investigadores en el RENACYT

#### `nivel`
Variable categórica ordinal  
Categoría de _Investigador Distinguido_ asignado por el CONCYTEC

#### `Fecha_de_inicio_de_vigencia`
Variable categórica nominal  
Ingreso del investigador en al registro RENACYT

#### `Fecha_fin_de_vigencia`
Variable categórica nominal  
Salida del investigador del registro RENACYT

#### `Rango_de_Edad`
Variable categórica ordinal  
Rango de edades en el que se encuentra el investigador

### Preguntas

#### ¿Es el estudio de interés para la audiencia?

El estudio tiene como objetivo dar a conocer la imagen del investigador
peruano y describir el grado de inclusión de las investigadoras en la comunidad.

#### ¿Qué información se desea aportar al final del estudio?

Se busca evidenciar la segregación de los de los investigadores según su sexo,
edad y categoría según el RENACYT.

#### ¿Es posible llegar a la información que se propone de manera específica y concreta?

Ya contamos con la base de datos, ahora necesitamos hacer uso de descriptores
numéricos y herramientas gráficas (aprendidas durante este curso) para hacer
legible la información obtenida.

## Segundo tema

## Analizar la percepción sobre las próximas elecciones municipales y regionales por parte de alumnos de la UTEC

### Relevancia
Después de 4 años se volverán a llevar a cabo las elecciones municipales y
regionales, en esta actividad se trata de realizar una votación democrática y
justa para elegir a los ciudadanos que ocupen los puestos de gobernadores regionales
y alcaldes provinciales y distritales.

Desde hace unos años el Perú está en un círculo vicioso de actos de corrupción y
una de las causas es la poca importancia que la población asigna a dar un voto
consciente e informado y se la da más relevancia al populismo de cada postulante
y a los favores políticos que posteriormente se comprueban como actos de
corrupción. Esta mala situación del país se debe más que todo a la gran
indiferencia que muestra la población hacia estos temas políticos. Es por esta
razón que decidimos proponer este tema tan importante, ya que al sugerir este
tema a los estudiantes de UTEC los incentivamos a tener un poco más de
importancia hacia el tema y así poder investigar a los candidatos más a fondo.
Consideramos que es de gran importancia saber cuánto saben los estudiantes del
tema y también como punto a favor de este trabajo estadístico podremos conocer
las preferencias políticas de cada uno de los encuestados.
 
### Factibilidad

En UTEC los estudiantes tienen un rango de edad de 17-25 años; los alumnos con
edades entre 17 y 19 años aún no han participado en elecciones anteriores, son
estos los que tomaremos como muestra para el estudio estadístico, por que es un
grupo de estudiantes que no llevan mucho tiempo en la universidad y tienen más
facilidad de acceder a contestar a nuestra encuesta, por otro lado tenemos un
gran número de estudiantes para encuestar.

### Descripción de variables 

#### `Edad`

Variable categórica ordinal  
Edad del estudiante

#### `Género`

Variable categórica nominal  
Género del estudiante

#### `Preferencia Política`

Variable categórica nominal  
Partido político preferido

#### `Escala Pensión UTEC`
Variable categórica nominal  
Escala económica UTEC

#### `Carrera Universitaria`
Variable categórica nominal  
Carrera que el estudiante está cursando

#### `Religión` 
Variable categórica nominal  
Religión del estudiante

#### `Lugar de nacimiento`
Variable categórica nominal  
Departamento en el que nació el estudiante

### Preguntas

#### ¿Es el estudio de interés para la audiencia?

Las elecciones municipales y regionales son uno de los eventos con mayor
relevancia que se llevarán a cabo este año en nuestro país. Además, al ser
estudiantes aún no participan en algún proceso electora estos tendrán más
interés y expectación en el tema.

#### ¿Qué información se desea aportar al final del estudio?

La información que se aportará al final del estudio será: la intención de voto
de los estudiantes de UTEC, la preferencia de los estudiantes de UTEC y su
experiencia al realizar la primera votación.

#### ¿Es posible llegar a la información que se propone de manera específica y concreta?

Sí es posible. Con ayuda de las encuestas y posteriormente un trabajo de
investigación obtendremos la información que estamos buscando. Usaremos como
principal método de recolección de datos a la encuesta y posiblemente alguno
más, los cuales nos ayudarán a nuestro estudio, ya que esta se responderá de
manera directa, por esta razón nosotros podremos confiar en los resultados que
obtengamos y de esa manera obtener al final una información concreta y segura.


## Tercer tema

Hallar una relación entre perfiles de estudiantes y su desempeño académico

### Relevancia

Como objetivo final se busca hallar una relación entre perfiles de estudiantes
(sus hábitos de estudio, horas de sueño, tiempo en llegar a la universidad,
nivel socioeconómico, etc) y las notas que obtenieron en ciclos pasados.

### Factibilidad

Los datos serán recopilados mediantes encuestas que se realizaran a estudiantes
de utec de diferentes ciclos y carreras, sin .

### Descripción de variables 

### `Edad`
Variable categórica ordinal  
Edad del estudiante en años

### `Género`
Variable categórica nominal  
Genero del estudiante, masculino o femenino

### `Ciclo`
Variable categórica ordinal  
Ciclo que el estudiante está cursando actualmente

### `Horas de sueño`
Variable numérica discreta  
Horas de sueño promedio que el estudiante recibe por noche. Medido en horas con
un decimal.

### `Escala Pensión UTEC`
Variable categórica ordinal  
Escala económica UTEC

### `Carrera Universitaria`
Variable categórica nominal  
Carrera que el estudiante está cursando

### `Duración del desplazamiento a la universidad` 
Variable numérica discreta  
Duración del desplazamiento diario a la universidad, representadas en horas más
grupos de 5 minutos

### `Distrito de residencia`
Variable categórica nominal  
Distrito en el que reside el alumno

### `Estado Sentimental`
Variable categórica nominal  
Si el estudiante se encuentra en una relación sentimental  
Opciones:  
- Soltero
- En una relación

### `Promedio del ciclo anterior`
Variable numérica discreta  
Promedio que el estudiante obtuvo el ciclo pasado, número con un decimal en el
rango [0, 20]

### `Nivel de captacion de cursos`
Variable categórica ordinal  
Ver qué tanto aprendió el alumno el ciclo anterior

### Preguntas

#### ¿Es el estudio de interés para la audiencia?

Sí, con los resultados se podrá saber que características poseen los alumnos con
mejor desempeño académico. De esta forma los alumnos que estén presentando
dificultades puedan obtener una referencia de lo que podrían hacer o aspectos en
los que podrían mejorar y ver así si es que quizá alguna de sus características
o hábitos sea causal de sus bajas notas.

#### ¿Qué información se desea aportar al final del estudio?

Encontrar qué variables están relacionadas con las notas y el nivel de
aprendizaje de los alumnos.

#### ¿Es posible llegar a la información que se propone de manera específica y concreta?

Claro, ya qué con el estudio de la base de datos y mediante el uso de
descriptores numéricos, gráficos y otras herramientas se pueda llegar a tener
información que sea robusta, legible y específica.
